server.port=8081
spring.application.name=acabou-mony-auth

# Conexão com o banco compartilhado
spring.datasource.url=jdbc:mysql://localhost:3306/db_acabou_mony?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true