server.port=8081
spring.application.name=acabou-mony-auth
spring.datasource.url=jdbc:mysql://localhost:3306/db_acabou_mony
spring.datasource.username=root
spring.datasource.password=senha
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Força o Hibernate a saber que é MySQL caso ele se perca
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=616adf6f27a668
spring.mail.password=1c1c452e80685a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.web=DEBUG