server.port=8088
jwt.secret=nhfc6HAxsZSzhyqZrVd7ANzR8zKLh2+u9gac7Mc3MCqcDoVZzQyXqzZYEKFXCoP9l6gkpi+VDiEZtD3eBBf4Eg==

services.auth.url=http://acabou-mony-auth:8081
services.account.url=http://acabou-mony-account:8082
services.card.url=http://acabou-mony-card:8083
services.transaction.url=http://acabou-mony-transaction:8084
services.auditing.url=http://acabou-mony-auditing:8085
