worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream auth_upstream {
        server localhost:8081;
    }
    upstream account_upstream {
        server localhost:8082;
    }
    upstream transaction_upstream {
        server localhost:8083;
    }
    upstream card_upstream {
        server localhost:8084;
    }
    upstream notificacao_upstream {
        server localhost:8085;
    }
    upstream auditing_upstream {
        server localhost:8086;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://auth_upstream;
        }

        location /api/accounts/ {
            proxy_pass http://account_upstream;
        }

        location /api/transactions/ {
            proxy_pass http://transaction_upstream;
        }

        location /api/cards/ {
            proxy_pass http://card_upstream;
        }

        location /api/notificacoes/ {
            proxy_pass http://notificacao_upstream;
        }

        location /api/auditing/ {
            proxy_pass http://auditing_upstream;
        }
    }
}